#! /bin/bash
echo "----------------------"
echo "A compilar o projecto."
echo "----------------------"

sh backup && cd ..
make refresh
# make trace

cd testes  && cp -f ../a.out ../y.output ./

echo
echo "--------------------"
echo "A Testar o projecto."
echo "--------------------"
echo "RESULTADOS: "> resultados.temp
for Z in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
	do
	 VAR1=test${Z}.in
	 VAR2=test${Z}.res
	 VAR3=test${Z}.out
	 printf "(teste ${Z}) \n"
	 ./a.out < $VAR1 > $VAR2
	 X=`diff $VAR2 $VAR3 | wc -l`
	if [ $X -eq 0 ]
	then 
	 echo $Z "ok" >> resultados.temp
	else 
	 echo $Z "not ok" >> resultados.temp
	fi
	done
echo 
cat resultados.temp
cd .. && make clean
